/*Desafio: criação da tabela de clientes*/
CREATE TABLE CLIENTES
(
CPF VARCHAR(11) NOT NULL,
NOME VARCHAR(100) NULL,
ENREDECO VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
CIDADE VARCHAR(50) NULL,
ESTADO VARCHAR(50) NULL,
CEP VARCHAR(8) NULL,
DATA_NASCIMENTO DATE NULL,
IDADE INT NULL,
GENERO VARCHAR(1) NULL,
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMAIRA_COMPRA BIT
)
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES_CPF 
PRIMARY KEY CLUSTERED (CPF)
