/*Desafio: incluindo registros a partir de outra tabela*/
INSERT INTO CLIENTES
	SELECT CPF, NOME, ENDERECO_1, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, GENERO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA
		FROM SUCOS_FRUTAS.DBO.TABELA_DE_CLIENTES
			WHERE (TABELA_DE_CLIENTES.CPF <> '1471156710') AND (TABELA_DE_CLIENTES.CPF <> '19290992743') AND (TABELA_DE_CLIENTES.CPF <> '2600586709')