/*Desafio: Alterando o volume de compra dos clientes INNER JOIN*/
UPDATE CLIENTES SET VOLUME_COMPRA = VOLUME_COMPRA * 1.30
FROM dbo.CLIENTES INNER JOIN dbo.VENDEDORES ON CLIENTES.BAIRRO = VENDEDORES.BAIRRO