/*Desafio: calculando a idade do cliente*/
CREATE TRIGGER TG_CLIENTES_IDADE
ON CLIENTES AFTER INSERT, UPDATE, DELETE
AS
BEGIN UPDATE CLIENTES SET IDADE = DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE());
END;